### PR TITLE
also take in account the gateways when checking for free to use node during pool creation

### LINKED ISSUE #148: Pool creation with FreeTFT fails on testnet freefarm
I'm trying to create a pool using currency FreeTFT on freefarm using chatflows but it fails with this error
```
failed to reserve pool. 500 Server Error: could not set up capacity escrow: none of the offered currencies are currently supported for url: https://explorer.testnet.grid.tf/api/v1/reservations/pools
```
this is my request body
```
'{"json": "{\\"pool_id\\": 0, \\"cus\\": 10, \\"sus\\": 10, \\"node_ids\\": [\\"3BwDVNRigau8Zk6BQkJt5PLxrHQnJ5NTfNvAtuubC1eS\\", \\"72CP8QPhMSpF7MbSvNR1TYZFbTnbRiuyvq5xwcoRNAib\\", \\"D1sY7tgHX6fVvjrpCotr4SmezVyRShLTufqhEpBQxK1v\\", \\"3dAnxcykEDgKVQdTRKmktggL2MZbm3CPSdS9Tdoy4HAF\\", \\"6m9gFPTYLRiCH7FD8yU5VWwXZdfegKUvXZgrJoS1EJfQ\\", \\"2fi9ZZiBGW4G9pnrN656bMfW6x55RSoHDeMrd9pgSA8T\\", \\"2m3nHPSAMyZFSeg5HPozic2NGBMtrXrBkhtNcVmd5Ss6\\", \\"A7FmQZ72h7FzjkJMGXmzLDFyfyxzitDZYuernGG97nv7\\", \\"6RZfnjuXVLFdtZh218hn4BLzsoKkTVpweqWECk5YUKud\\"], \\"currencies\\": [\\"FreeTFT\\"]}", "data_reservation": {"pool_id": 0, "cus": 10, "sus": 10, "node_ids": ["3BwDVNRigau8Zk6BQkJt5PLxrHQnJ5NTfNvAtuubC1eS", "72CP8QPhMSpF7MbSvNR1TYZFbTnbRiuyvq5xwcoRNAib", "D1sY7tgHX6fVvjrpCotr4SmezVyRShLTufqhEpBQxK1v", "3dAnxcykEDgKVQdTRKmktggL2MZbm3CPSdS9Tdoy4HAF", "6m9gFPTYLRiCH7FD8yU5VWwXZdfegKUvXZgrJoS1EJfQ", "2fi9ZZiBGW4G9pnrN656bMfW6x55RSoHDeMrd9pgSA8T", "2m3nHPSAMyZFSeg5HPozic2NGBMtrXrBkhtNcVmd5Ss6", "A7FmQZ72h7FzjkJMGXmzLDFyfyxzitDZYuernGG97nv7", "6RZfnjuXVLFdtZh218hn4BLzsoKkTVpweqWECk5YUKud"], "currencies": ["FreeTFT"]}, "customer_tid": 416, "customer_signature": "f607e63ae77c5288f64ec3e0239f0be114e13074195f6847f8035bad3898b880a910fb44e089b3e4ca6fbbf31932f3be943b4617bf9d95f95b604acc20fc5b0d"}'
```

### PR DESCRIPTION
**Pull request by zaibon**
fixes #148

### CODE REVIEW

File: pkg/workloads/reservation.go [hunk 1]
```diff
@@ -1235,3 +1219,35 @@ func userCanSign(userTid int64, req workloads.SigningRequest, signatures []workl
...
+		return false, err
+	}
+	freeNodes += count
+
+	log.Info().
+		Int("requested_nodes", len(nodeIDs)).
+		Int64("free_nodes", freeNodes).
+		Msg("distribution of free nodes in capacity reservation")
+
+	return freeNodes > int64(len(nodeIDs)), nil
```
Comment (DylanVerstraete) [inline pkg/workloads/reservation.go:1252]: Should it not be `>=` because this value can be equal as well?

Comment (zaibon) [reply pkg/workloads/reservation.go:1252]: right
