### PR TITLE
change how delete and provision signature are accepted and verified

### LINKED ISSUE #141: deleting migrated workloads fails
when deleting migrated workloads I get some problems
this is a container
```python
JS-NG> j.sals.zos.workloads.decomission(462712)                                                                                                                                                                    
2020-08-03 14:19:24.729 | ERROR    | jumpscale.tools.errorhandler.errorhandler:_handle_exception:55 - requests.exceptions.HTTPError: 500 Server Error: bulk write error: [{[{Cannot apply $pull to a non-array value}]}, {<nil>}] for url: https://explorer.testnet.grid.tf/api/v1/reservations/workloads/462712/sign/delete
```

this is the data that was sent
```json
{"signature": "e31fa72db304f0fb8e016497b0801d7bc5ed48d769081311743f251e2744b1b3d6cbafe701dc9a7e198f918ff96f50f13aca313563be32f802adc5c892fe0a0c", "tid": 416, "epoch": 1596459521}
```

this is a network

```python
JS-NG> j.sals.zos.workloads.decomission(462747)                                                                                                                                                                    
2020-08-03 14:18:09.852 | ERROR    | jumpscale.tools.errorhandler.errorhandler:_handle_exception:55 - requests.exceptions.HTTPError: 401 Client Error: signature not required for '416' for url: https://explorer.testnet.grid.tf/api/v1/reservations/workloads/462747/sign/delete
```

the data that was sent
```json                                                      
{"signature": "0f059c2c1d26b28f7ddb1dc3ff40ef304a0784c85181df197173c61b317b2a72b705c95902e74ff2abba67780f535550daa0fe1a66eecb309e115ecee9351b00", "tid": 416, "epoch": 1596459623}
```

### PR DESCRIPTION
**Pull request by zaibon**
After this commit, user that are requested in the delete or provision
consensus are only able to push a signature once.

If they already have a signature registered and try to put a new one, an
400 bad request error will be returned by the API.

This change allow to simplify the way we deal with signature array
internally and should prevent issue like #141

fixes #141

### CODE REVIEW

File: pkg/workloads/types/reservation.go [hunk 1]
```diff
@@ -701,31 +701,17 @@ const (
...
-			}),
-		mongo.NewUpdateOneModel().SetFilter(filter).SetUpdate(
-			bson.M{
-				"$addToSet": bson.M{
-					string(mode): signature,
-				},
-			}),
-	}, options.BulkWrite().SetOrdered(true))
+	_, err := col.UpdateOne(ctx, filter, bson.M{
+		"$push": bson.M{
```
Comment (muhamadazmy) [inline pkg/workloads/types/reservation.go:711]: Are u sure $push can work on a `nil` array in mongo ? Also because there is no race grantees, I will also change where we check the signature count to make sure a user is not counted twice if somehow 2 signtaures of the same user managed to end up in that array (imagine pushing the same signtuare twice but at exact same time)

Comment (zaibon) [reply pkg/workloads/types/reservation.go:711]: I'm still not sure where the nill array issue comes from. I'm suspecting the migration code did that.

**Comment by zaibon** [comment]
@muhamadazmy I think I've covered all the cases that could lead to a nil array.
We might still need to manually ensure there are not already such a null array  in the db and update that is needed.
