### PR TITLE
fixes inconsistent loading of nodes and farms, fixes #45

### LINKED ISSUE #45: Duplicate Nodes Showing on TF Explorer
After upgrading nodes to 2.0 duplicates are appearing on https://explorer.grid.tf/
Farm ID: dec_hk_t1
dec_hk-t1 duplicated nodes

### PR DESCRIPTION
**Pull request by DylanVerstraete**

### CODE REVIEW

File: frontend/src/store/transaction.js [hunk 1]
```diff
@@ -49,30 +50,84 @@ export default ({
       context.commit('setUser', response.data)
     },
     getRegisteredNodes (context, params) {
-      let page = params.page || context.state.nodePage
+      let page = context.state.nodePage
```
Comment (zaibon) [inline frontend/src/store/transaction.js:53]: this will always be 1 here no ? since we always get all the nodes ?

File: frontend/src/store/transaction.js [hunk 2]
```diff
@@ -49,30 +50,84 @@ export default ({
...
+          })
+          .finally(() => {
+            context.commit('setTotalSpecs', context.state.registeredNodes)
+            context.commit('setNodesLoading', false)
+          })
       })
     },
     getRegisteredFarms (context, params) {
-      let page = params.page || context.state.farmPage
+      let page = context.state.nodePage
```
Comment (zaibon) [inline frontend/src/store/transaction.js:80]: this will always be 1 here no ? since we always get all the farms ?

File: frontend/src/store/transaction.js [hunk 3]
```diff
@@ -49,30 +50,84 @@ export default ({
...
+            })
+          })
+          .finally(() => {
+            context.commit('setAmountOfFarms', context.state.registeredFarms)
+            context.commit('setFarmsLoading', false)
+          })
       })
     },
     getRegisteredGateways (context, params) {
       let page = params.page || context.state.gatewayPage
```
Comment (zaibon) [inline frontend/src/store/transaction.js:107]: this will always be 1 here no ? since we always get all the gateway ?

File: frontend/src/store/transaction.js [hunk 4]
```diff
@@ -49,30 +50,84 @@ export default ({
...
+      let page = context.state.nodePage
       if (!page) return
 
-      tfService.getNodes(undefined, params.size, page).then(response => {
+      const getNodes = (page) => {
+        return tfService.getNodes(undefined, params.size, page)
+      }
+
+      getNodes(page).then(response => {
         context.commit('setRegisteredNodes', response)
```
Comment (zaibon) [inline frontend/src/store/transaction.js:61]: why do we commit here ? shouldn't we just commit once we have fetch all the pages?

File: frontend/src/store/transaction.js (hunk 1 above)
Comment (DylanVerstraete) [reply frontend/src/store/transaction.js:53]: No, it will increment if there are more pages https://github.com/threefoldtech/tfexplorer/blob/b2b43649918dd387125ee886485db85bbf08f05e/frontend/src/store/transaction.js#L157

File: frontend/src/store/transaction.js (hunk 2 above)
Comment (DylanVerstraete) [reply frontend/src/store/transaction.js:80]: No, it will increment if there are more pages https://github.com/threefoldtech/tfexplorer/blob/b2b43649918dd387125ee886485db85bbf08f05e/frontend/src/store/transaction.js#L165

File: frontend/src/store/transaction.js (hunk 3 above)
Comment (DylanVerstraete) [reply frontend/src/store/transaction.js:107]: No, it will increment if there are more pages https://github.com/threefoldtech/tfexplorer/blob/b2b43649918dd387125ee886485db85bbf08f05e/frontend/src/store/transaction.js#L173

File: frontend/src/store/transaction.js (hunk 4 above)
Comment (DylanVerstraete) [reply frontend/src/store/transaction.js:61]: not sure, maybe we can commit in when the promises are resolved

Comment (DylanVerstraete) [reply frontend/src/store/transaction.js:61]: Doesn't work well, going to stick with what we have right now.
